train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-other-500"
  instance_transforms: ${transforms.instance_transforms.train_augs}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-other"
  instance_transforms: ${transforms.instance_transforms.inference}
