defaults:
  - model: deepspeech2
  - metrics: inference
  - datasets: inference_clean
  - dataloader: example
  - transforms: inference
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  use_torchaudio_ctc: True
  lm_path: saved/4-gram.arpa
  lm_weight: 0.5
  top_k_beams: 512
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  override: True
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
